### ISSUE TITLE
User can add a reference of type inproceeding using the form

### ISSUE THREAD

**Issue by OGesko** [lamtonylam/ohtuminiprojekti#1]
Required and optional fields of inproceedings: https://bibtex.eu/types/inproceedings/

**Comment by Seba686** [comment]
Acceptance criteria:

- User can navigate to input form easily.
- User can add reference of type inproceedings with only required fields.
- User can add reference of type inproceedings with required and some optional fields.
- User gets confirmation that the information has been saved.
